# Grafana Datasource Provisioning
# This file auto-configures the Prometheus datasource on Grafana startup
#
# NOTE: URL must include /prometheus path because Prometheus is configured
# with --web.external-url=/prometheus/

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    # Include /prometheus path - matches Prometheus --web.external-url setting
    url: http://prometheus:9090/prometheus
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: "2.x.x"
